### ISSUE TITLE
[BUG] The pokemon  doesn't spawn 

### ISSUE THREAD

**Issue by mikprofilodi** [brysondev/Legendary-Encounters#1]
hello i wanted to try the datapack but in trying to spawan mewtwo, rayquaza and zapdos would not go. Can you find the problem?

**Comment by brysondev** [comment]
Hello. Can you please give me some more details about this problem so I can recreate it?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Version [e.g. 22]

**Additional context**

**Comment by mikprofilodi** [comment]
i use the datapack in a server multiplayer and we can spawn the mewtwo using the netherstar the pokemon don't spawn. i don't know if the other leggendary spawn becouse i try with mewtwo. i don't have acces a console server but i'm helping the staff.

**Comment by brysondev** [comment]
![image](https://github.com/brysondev/Legendary-Encounters/assets/13501615/925ccab9-77bb-4777-8773-dfe325e5065a)

closing, addressed in description on modrinth.
